import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# 1. Read CSV data generated by C++
file_path = r'C:\myCodes\C++\storage\simu\lsm_results.csv'

try:
    df = pd.read_csv(file_path)
except FileNotFoundError:
    print(f"Error: file not found {file_path}, please check the path.")
    exit()

# 2. Data pivot alignment
# Use Layer3_Retry_Prob as baseline to align all Mode data
pivot_df = df.pivot(index='Layer3_Retry_Prob', columns='Mode')

# 3. Calculate improvement percentage (%)
def calc_improvement(base, target):
    # Use np.where to avoid division by zero error
    return np.where(base == 0, 0, (base - target) / base * 100)

imp_data = pd.DataFrame(index=pivot_df.index)
imp_data['X_axis'] = pivot_df.index

# [New step] Calculate FP_L0 + FP_L1 + FP_L2 and add to pivot_df for unified processing
fp_sum_data = pivot_df['FP_L0'] + pivot_df['FP_L1'] + pivot_df['FP_L2']
for mode in fp_sum_data.columns:
    pivot_df[('FP_L012_Sum', mode)] = fp_sum_data[mode]

# Define all metrics with corresponding titles and filenames (added last two items)
percentiles = [
    ('Mean_Latency_us', 'Mean Latency', 'lsm_Mean_Latency_improvement.png'),
    ('P50_us', 'P50 Latency', 'lsm_p50_improvement.png'),
    ('P99_us', 'P99 Latency', 'lsm_p99_improvement.png'),
    ('P99.9_us', 'P99.9 Latency', 'lsm_p99_9_improvement.png'),
]

# Calculate all improvement rates
for col, _, _ in percentiles:
    imp_data[f'{col}_M2_vs_M1'] = calc_improvement(pivot_df[col]['Mode 1 (Uniform)'], pivot_df[col]['Mode 2 (Monkey)'])
    imp_data[f'{col}_M3_vs_M1'] = calc_improvement(pivot_df[col]['Mode 1 (Uniform)'], pivot_df[col]['Mode 3 (Age-aware)'])
    imp_data[f'{col}_M3_vs_M2'] = calc_improvement(pivot_df[col]['Mode 2 (Monkey)'], pivot_df[col]['Mode 3 (Age-aware)'])

# Ensure X-axis is sorted to avoid chaotic line connections
imp_data = imp_data.sort_values(by='X_axis')

# Define colors
color_m2_m1 = '#2ca02c'  # Green: Mode 2 vs Mode 1
color_m3_m1 = '#1f77b4'  # Blue: Mode 3 vs Mode 1
color_m3_m2 = '#ff7f0e'  # Orange: Mode 3 vs Mode 2

# Set output directory
output_dir = r'C:\myCodes\C++\storage\simu'

# 4. Draw individual plots independently and save
for col_name, title, filename in percentiles:
    plt.figure(figsize=(9, 6))
    
    x = imp_data['X_axis'].values
    
    # Draw three trend lines
    plt.plot(x, imp_data[f'{col_name}_M2_vs_M1'], marker='^', linewidth=2, linestyle='--', color=color_m2_m1, label='Mode 2 vs Mode 1')
    plt.plot(x, imp_data[f'{col_name}_M3_vs_M1'], marker='o', linewidth=2.5, color=color_m3_m1, label='Mode 3 vs Mode 1')
    plt.plot(x, imp_data[f'{col_name}_M3_vs_M2'], marker='s', linewidth=2.5, color=color_m3_m2, label='Mode 3 vs Mode 2')
    
    # Chart styling and details
    plt.title(f'{title} Relative Improvement (%)', fontsize=14, fontweight='bold')
    plt.xlabel('Retry Probability', fontsize=12)
    plt.ylabel('Improvement (%)', fontsize=12)
    
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend(loc='best', fontsize=10)
    
    # Restrict P50 Y-axis bounds to mitigate minor visual noise
    if col_name == 'P50_us':
        plt.ylim(-5, 20) 
        
    plt.tight_layout()
    
    # Save the generated figure
    save_path = os.path.join(output_dir, filename)
    plt.savefig(save_path, dpi=300)
    print(f"Generated plot: {save_path}")
    
    plt.show()